# ════════════════════════════════════════════════════════════════
# PRAJNA — prajna_app.py
# Generated by Cell 8 in Colab notebook
# After running this cell, run the logo injection cell
# ════════════════════════════════════════════════════════════════

# ── [SECTION: IMPORTS] ──────────────────────────────────────────
import streamlit as st
from neo4j import GraphDatabase
from groq import Groq
from pyvis.network import Network
import streamlit.components.v1 as components
import os, json, pandas as pd, io
from collections import defaultdict
from datetime import datetime, timezone
from fpdf import FPDF
# ── [END: IMPORTS] ──────────────────────────────────────────────


# ── [SECTION: CREDENTIALS] ──────────────────────────────────────
NEO4J_URI      = os.environ.get("NEO4J_URI")      or st.secrets.get("NEO4J_URI")
NEO4J_USERNAME = os.environ.get("NEO4J_USERNAME") or st.secrets.get("NEO4J_USERNAME")
NEO4J_PASSWORD = os.environ.get("NEO4J_PASSWORD") or st.secrets.get("NEO4J_PASSWORD")
GROQ_API_KEY   = os.environ.get("GROQ_API_KEY")   or st.secrets.get("GROQ_API_KEY")
# ── [END: CREDENTIALS] ──────────────────────────────────────────


# ── [SECTION: LOGO PLACEHOLDER] ─────────────────────────────────
# Replaced by logo injection cell after %%writefile runs
LOGO_B64 = "{LOGO_B64}"
# ── [END: LOGO PLACEHOLDER] ─────────────────────────────────────


# ── [SECTION: CONNECTIONS] ──────────────────────────────────────
@st.cache_resource
def get_driver():
    return GraphDatabase.driver(NEO4J_URI, auth=(NEO4J_USERNAME, NEO4J_PASSWORD))

@st.cache_resource
def get_groq():
    return Groq(api_key=GROQ_API_KEY)

driver      = get_driver()
groq_client = get_groq()
# ── [END: CONNECTIONS] ──────────────────────────────────────────


# ── [SECTION: UTILITY FUNCTIONS] ────────────────────────────────
def get_week_key():
    now = datetime.now(timezone.utc)
    return f"{now.year}-W{now.strftime('%W')}"

def ask_groq(prompt, max_tokens=600):
    # Uses versatile model for all intelligence briefs
    r = groq_client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=[{"role": "user", "content": prompt}],
        max_tokens=max_tokens, temperature=0.3
    )
    return r.choices[0].message.content

def sanitize(text):
    # Replaces unicode characters that fpdf2 cannot handle
    # Called on ALL text before writing to PDF
    if not text:
        return ""
    replacements = {
        "\u2014": "-", "\u2013": "-", "\u2012": "-",
        "\u2018": "'", "\u2019": "'", "\u201a": "'",
        "\u201c": '"', "\u201d": '"', "\u201e": '"',
        "\u2022": "*", "\u2023": "*", "\u25aa": "*",
        "\u2026": "...", "\u00a0": " ", "\u2032": "'",
        "\u00e9": "e", "\u00e8": "e", "\u00ea": "e",
        "\u00e0": "a", "\u00e2": "a", "\u00f4": "o",
        "\u00fb": "u", "\u00fc": "u", "\u00ef": "i",
        "\u00e7": "c", "\u00f1": "n",
    }
    for orig, repl in replacements.items():
        text = text.replace(orig, repl)
    text = text.encode("latin-1", errors="replace").decode("latin-1")
    # Break words longer than 60 chars to prevent fpdf crash
    words = text.split(" ")
    broken = []
    for w in words:
        if len(w) > 60:
            broken.append(w[:60] + " " + w[60:])
        else:
            broken.append(w)
    return " ".join(broken)

def pdf_write_line(pdf, line):
    # Safe single-line writer for PDF — wraps in try/except
    # Detects header lines vs body lines for styling
    line = line.strip()
    if not line:
        pdf.ln(3)
        return
    is_header = any(line.startswith(x) for x in [
        "STORY", "BOTTOM LINE", "WEEK", "EXECUTIVE",
        "STRATEGIC RISK", "HIGH RISK", "MEDIUM RISK", "OPPORTUNITY"
    ])
    if is_header:
        pdf.set_font("Helvetica", "B", 10)
        pdf.set_text_color(232, 213, 163)
    else:
        pdf.set_font("Helvetica", "", 10)
        pdf.set_text_color(180, 195, 210)
    try:
        pdf.multi_cell(0, 6, line)
    except Exception:
        try:
            pdf.multi_cell(0, 6, line[:200])
        except Exception:
            pass
# ── [END: UTILITY FUNCTIONS] ────────────────────────────────────


# ── [SECTION: PDF GENERATOR] ────────────────────────────────────
# Called from Tab 5 after detailed_brief is generated by Groq
# Returns bytes object for st.download_button
def generate_pdf_brief(brief_week, top_pairs, headlines, brief_text, names):
    brief_week_safe = sanitize(brief_week)
    brief_text_safe = sanitize(brief_text)

    class PDF(FPDF):
        def header(self):
            self.set_fill_color(10, 12, 15)
            self.rect(0, 0, 210, 297, 'F')
            self.set_font("Helvetica", "B", 16)
            self.set_text_color(232, 213, 163)
            self.cell(0, 12, "PRAJNA", ln=True, align="C")
            self.set_font("Helvetica", "", 8)
            self.set_text_color(74, 106, 138)
            self.cell(0, 6, "STRATEGIC INTELLIGENCE ENGINE  |  INDIA INNOVATES 2026  |  TEAM IIMC", ln=True, align="C")
            self.set_draw_color(28, 42, 56)
            self.line(15, 28, 195, 28)
            self.ln(4)

        def footer(self):
            self.set_y(-15)
            self.set_font("Helvetica", "", 7)
            self.set_text_color(42, 58, 74)
            self.cell(0, 10, "PRAJNA  |  " + brief_week_safe + "  |  CONFIDENTIAL  |  Page " + str(self.page_no()), align="C")

    pdf = PDF()
    pdf.set_auto_page_break(auto=True, margin=20)
    pdf.add_page()

    # Title block
    pdf.set_font("Helvetica", "B", 13)
    pdf.set_text_color(232, 213, 163)
    pdf.cell(0, 8, "WEEKLY INTELLIGENCE BRIEF  -  " + brief_week_safe, ln=True, align="C")
    pdf.set_font("Helvetica", "", 8)
    pdf.set_text_color(74, 106, 138)
    pdf.cell(0, 6, str(len(names)) + " entities  |  " + str(len(top_pairs)) + " signal pairs  |  AUTO-GENERATED BY PRAJNA", ln=True, align="C")
    pdf.ln(6)

    # Gold divider
    pdf.set_draw_color(200, 169, 110)
    pdf.set_line_width(0.5)
    pdf.line(15, pdf.get_y(), 195, pdf.get_y())
    pdf.ln(6)

    # Main brief body
    for line in brief_text_safe.split("\n"):
        pdf_write_line(pdf, line)
    pdf.ln(6)

    # Source data section
    pdf.set_draw_color(28, 42, 56)
    pdf.set_line_width(0.3)
    pdf.line(15, pdf.get_y(), 195, pdf.get_y())
    pdf.ln(4)
    pdf.set_font("Helvetica", "B", 9)
    pdf.set_text_color(74, 106, 138)
    pdf.cell(0, 6, "GRAPH SIGNAL PAIRS  -  SOURCE DATA", ln=True)
    pdf.ln(2)

    for p in top_pairs:
        pdf.set_font("Helvetica", "B", 9)
        pdf.set_text_color(200, 169, 110)
        try:
            pdf.cell(0, 5, "  " + sanitize(p["e1"]) + "  <>  " + sanitize(p["e2"]), ln=True)
        except Exception:
            pass
        arts = headlines.get(p["e1"] + " and " + p["e2"], [])
        for a in arts:
            pdf.set_font("Helvetica", "", 8)
            pdf.set_text_color(90, 122, 154)
            try:
                pdf.multi_cell(0, 5, "    [" + sanitize(a["source"]) + "]  " + sanitize(a["title"]))
            except Exception:
                pass
        pdf.ln(1)

    # Disclaimer
    pdf.ln(4)
    pdf.line(15, pdf.get_y(), 195, pdf.get_y())
    pdf.ln(4)
    pdf.set_font("Helvetica", "I", 7)
    pdf.set_text_color(42, 58, 74)
    pdf.multi_cell(0, 5, "Auto-generated by Prajna using knowledge graph analysis of real-time news data. For strategic assessment purposes only.")

    buf = io.BytesIO()
    pdf.output(buf)
    buf.seek(0)
    return buf.read()
# ── [END: PDF GENERATOR] ────────────────────────────────────────


# ── [SECTION: NEO4J QUERY FUNCTIONS] ────────────────────────────
@st.cache_data(ttl=300)
def get_stats():
    # Returns: articles, entities, co-occurrence rels, semantic rels
    with driver.session() as session:
        a = session.run("MATCH (a:Article) RETURN count(a) as c").single()["c"]
        e = session.run("MATCH (e:Entity)  RETURN count(e) as c").single()["c"]
        r = session.run("MATCH ()-[r:CO_OCCURS_WITH]->() RETURN count(r) as c").single()["c"]
        s = session.run("MATCH ()-[r:RELATES_TO]->() RETURN count(r) as c").single()["c"]
    return a, e, r, s

@st.cache_data(ttl=300)
def get_available_weeks():
    from datetime import datetime, timedelta
    with driver.session() as session:
        result = session.run(
            "MATCH (a:Article) RETURN DISTINCT a.week as week ORDER BY week DESC"
        ).data()
    weeks = [r["week"] for r in result if r["week"]]

    def week_label(wk):
        try:
            # Parse "2026-W09" → Monday of that week
            monday = datetime.strptime(wk + "-1", "%Y-W%W-%w")
            sunday = monday + timedelta(days=6)
            return f"{wk}  ({monday.strftime('%d %b')} – {sunday.strftime('%d %b %Y')})"
        except:
            return wk

    return [week_label(w) for w in weeks]

def strip_week_label(w):
    if w and "(" in w:
        return w.split("(")[0].strip()
    return w

def get_graph_context(keywords):
    # Tab 1 — queries RELATES_TO for semantic context fed into Groq prompt
    with driver.session() as session:
        result = session.run("""
            MATCH (e:Entity)-[r:RELATES_TO]-(other:Entity)
            WHERE any(kw IN $kw WHERE toLower(e.name) CONTAINS toLower(kw))
            RETURN e.name AS e1, other.name AS e2, r.type AS rel, r.count AS strength
            ORDER BY r.count DESC LIMIT 20
        """, {"kw": keywords})
        return [(r["e1"], r["e2"], r["rel"], r["strength"]) for r in result]

def get_articles(keywords):
    # Tab 1 — fetches supporting article titles and sources for brief
    with driver.session() as session:
        result = session.run("""
            MATCH (a:Article)-[:MENTIONS]->(e:Entity)
            WHERE any(kw IN $kw WHERE toLower(e.name) CONTAINS toLower(kw))
            RETURN DISTINCT a.title AS title, a.source AS source LIMIT 5
        """, {"kw": keywords})
        return [(r["title"], r["source"]) for r in result]

def get_trajectory(e1, e2):
    # Tab 2 — weekly co-occurrence counts between two named entities
    with driver.session() as session:
        rows = session.run("""
            MATCH (a:Article)-[:MENTIONS]->(x:Entity {name:$e1})
            MATCH (a)-[:MENTIONS]->(y:Entity {name:$e2})
            WHERE a.week IS NOT NULL
            RETURN a.week AS week, COUNT(a) AS cnt
            ORDER BY week
        """, {"e1": e1, "e2": e2}).data()
    if not rows:
        return None, None
    wc = {r["week"]: r["cnt"] for r in rows}
    return sorted(wc.items()), sum(wc.values())

def get_semantic_relations(entity):
    # Tab 3 Entity Semantic Profile
    # outgoing = entity acts on others, incoming = others act on entity
    with driver.session() as session:
        outgoing = session.run("""
            MATCH (e:Entity {name:$name})-[r:RELATES_TO]->(other:Entity)
            RETURN other.name AS target, r.type AS rel, r.count AS cnt
            ORDER BY cnt DESC LIMIT 15
        """, {"name": entity}).data()
        incoming = session.run("""
            MATCH (other:Entity)-[r:RELATES_TO]->(e:Entity {name:$name})
            RETURN other.name AS source, r.type AS rel, r.count AS cnt
            ORDER BY cnt DESC LIMIT 15
        """, {"name": entity}).data()
    return outgoing, incoming

def find_path(e1, e2):
    # Tab 3 Path Query — shortest path via CO_OCCURS_WITH (max 4 hops)
    with driver.session() as session:
        result = session.run("""
            MATCH path = shortestPath(
                (a:Entity {name:$e1})-[:CO_OCCURS_WITH*1..4]-(b:Entity {name:$e2})
            )
            RETURN [node IN nodes(path) | node.name] AS nodes,
                   [rel IN relationships(path) | rel.count] AS strengths,
                   length(path) AS hops
        """, {"e1": e1, "e2": e2}).single()
    if not result:
        return None
    return {"nodes": result["nodes"], "strengths": result["strengths"], "hops": result["hops"]}
# ── [END: NEO4J QUERY FUNCTIONS] ────────────────────────────────


# ── [SECTION: SURGE DETECTION] ──────────────────────────────────
# Blocklist — media orgs and generic terms excluded from surge results
BLOCKLIST = {
    "Supreme","Asian","Islam","American","European","Western","Eastern",
    "BBC","CNN","Reuters","Bloomberg","NDTV","Mint","Hindu","Express",
    "ANI","PTI","AFP","AP","Wire","Tribune","Times","Globe","Newswire", "Guardian", "Reuters", "Bloomberg", "BBC", "CNN", "AP", "AFP",
    "NewsAPI", "NDTV", "Mint", "Times", "Tribune", "Wire",
    "Monday", "Tuesday", "Wednesday", "Thursday", "Friday",
    "January", "February", "March", "April", "May", "June",
    "July", "August", "September", "October", "November", "December",
    "New Year", "World", "Global", "International", "National"
}

def detect_surges(threshold=1.5, top_n=5):
    # Compares current week article mentions vs historical per-week baseline
    # Returns entities surging above threshold x baseline, sorted by ratio
    week_key = get_week_key()
    with driver.session() as session:
        results = session.run("""
            MATCH (a:Article)-[:MENTIONS]->(e:Entity)
            WHERE a.week IS NOT NULL
            AND e.type IN ["GPE","ORG","PERSON","NORP"]
            RETURN e.name AS entity, e.type AS type,
                   a.week AS week, COUNT(a) AS cnt
        """).data()
    entity_weekly = defaultdict(lambda: defaultdict(int))
    entity_type   = {}
    for row in results:
        e = row["entity"]
        entity_type[e] = row["type"]
        entity_weekly[e][row["week"]] += row["cnt"]
    entity_total = {e: sum(w.values()) for e, w in entity_weekly.items()}
    surges = []
    for entity, weekly in entity_weekly.items():
        if entity in BLOCKLIST:                                           continue
        if entity_total[entity] < 8:                                      continue
        if len(entity) > 35:                                              continue
        if any(c.isdigit() for c in entity):                              continue
        if entity_type.get(entity) not in {"GPE","ORG","PERSON","NORP"}:  continue
        weeks = sorted(weekly.keys())
        if not weeks or weeks[-1] != week_key:                            continue
        latest   = weekly[weeks[-1]]
        hist     = [weekly[w] for w in weeks[:-1]]
        baseline = sum(hist)/len(hist) if hist else latest
        if baseline == 0: continue
        ratio = latest / baseline
        if ratio >= threshold:
            surges.append({
                "entity":   entity,
                "type":     entity_type.get(entity, ""),
                "latest":   latest,
                "baseline": round(baseline, 1),
                "ratio":    round(ratio, 2),
                "total":    entity_total[entity]
            })
    surges.sort(key=lambda x: x["ratio"], reverse=True)
    return surges[:top_n]
# ── [END: SURGE DETECTION] ──────────────────────────────────────


# ── [SECTION: RELATION COLOR MAP] ───────────────────────────────
# Edge colors for semantic graph
# Red=conflict, Orange=military, Yellow=sanctions/oppose
# Blue=trade, Green=alliance, Purple=governance, Teal=diplomacy
RELATION_COLORS = {
    "THREATENS":              "#C87B6A",
    "ATTACKS":                "#C87B6A",
    "CONFLICTS_WITH":         "#C87B6A",
    "DEFEATS":                "#C87B6A",
    "SUPPLIES_WEAPONS_TO":    "#C8956A",
    "DEPLOYS_FORCES_IN":      "#C8956A",
    "OCCUPIES":               "#C8956A",
    "SANCTIONS":              "#C8B86A",
    "ACCUSES":                "#C8B86A",
    "CONDEMNS":               "#C8B86A",
    "OPPOSES":                "#C8B86A",
    "PROTESTS_AGAINST":       "#C8B86A",
    "DISPUTES_TERRITORY_WITH":"#C8B86A",
    "EXPELS":                 "#C8B86A",
    "IMPORTS_FROM":           "#6B8CAE",
    "EXPORTS_TO":             "#6B8CAE",
    "TRADES_WITH":            "#6B8CAE",
    "COMPETES_WITH":          "#6B8CAE",
    "DEPENDS_ON":             "#6B8CAE",
    "OWNS":                   "#6B8CAE",
    "ALLIES_WITH":            "#4A8A6A",
    "SUPPORTS":               "#4A8A6A",
    "COOPERATES_WITH":        "#4A8A6A",
    "FUNDS":                  "#4A8A6A",
    "RECOGNIZES":             "#4A8A6A",
    "GOVERNS":                "#8A6AAE",
    "CONTROLS":               "#8A6AAE",
    "LEADS":                  "#8A6AAE",
    "ELECTS":                 "#8A6AAE",
    "NEGOTIATES_WITH":        "#4A8AAA",
    "MEDIATES":               "#4A8AAA",
    "INFLUENCES":             "#4A8AAA",
    "INVESTS_IN":             "#4A8AAA",
}
# ── [END: RELATION COLOR MAP] ───────────────────────────────────


# ── [SECTION: GRAPH VISUALIZER] ─────────────────────────────────
# Builds PyVis network graph
# mode="semantic"     → RELATES_TO edges, colored by type, labels on hover only
# mode="cooccurrence" → CO_OCCURS_WITH edges, sized by count, week-filterable
# keyword=comma-separated string → seeds + direct neighbors only
# week="2026-WXX"    → co-occurrence mode only, ignored in semantic mode
def build_graph_visual(keyword=None, week=None, mode="semantic"):
    TYPE_COLORS = {
        "GPE":    "#C8A96E",
        "ORG":    "#6B8CAE",
        "PERSON": "#A8C5A0",
        "NORP":   "#B8956A",
        "LOC":    "#8AABBA",
        "EVENT":  "#C47B6E"
    }

    # Parse comma-separated filter into list of lowercase strings
    kw_list = [k.strip().lower() for k in keyword.split(",") if k.strip()] if keyword else []

    with driver.session() as session:

        if mode == "semantic":
            if kw_list:
                # Step 1 — find seed entities matching any keyword
                seed_results = session.run("""
                    MATCH (e:Entity)
                    WHERE any(kw IN $kw_list WHERE toLower(e.name) CONTAINS kw)
                    RETURN e.name AS name, e.type AS type
                    LIMIT 20
                """, {"kw_list": kw_list})
                seeds = [r["name"] for r in seed_results]

                if not seeds:
                    # No matches — fall back to full top-40 graph
                    res = session.run("""
                        MATCH (node:Entity)-[r:RELATES_TO]-()
                        WITH node, COUNT(r) AS conn
                        ORDER BY conn DESC LIMIT 25
                        RETURN node.name AS name, node.type AS type, conn
                    """)
                    top = {r["name"]: r for r in res}
                else:
                    # Step 2 — get direct neighbors of seeds via RELATES_TO
                    nb_results = session.run("""
                        MATCH (e:Entity)-[:RELATES_TO]-(nb:Entity)
                        WHERE e.name IN $seeds
                        WITH COLLECT(DISTINCT nb.name) AS neighbors
                        RETURN neighbors
                    """, {"seeds": seeds})
                    nb_row    = nb_results.single()
                    neighbors = nb_row["neighbors"] if nb_row else []
                    all_names = list(set(seeds + neighbors))

                    # Step 3 — get metadata for seeds + neighbors
                    node_results = session.run("""
                        MATCH (node:Entity)-[r:RELATES_TO]-()
                        WHERE node.name IN $all_names
                        WITH node, COUNT(r) AS conn
                        ORDER BY conn DESC LIMIT 40
                        RETURN node.name AS name, node.type AS type, conn
                    """, {"all_names": all_names})
                    top = {r["name"]: r for r in node_results}
            else:
                # No filter — top 40 by semantic connection count
                res = session.run("""
                    MATCH (node:Entity)-[r:RELATES_TO]-()
                    WITH node, COUNT(r) AS conn
                    ORDER BY conn DESC LIMIT 40
                    RETURN node.name AS name, node.type AS type, conn
                """)
                top = {r["name"]: r for r in res}

            # Get semantic edges between top nodes only
            rels = session.run("""
                MATCH (e1:Entity)-[r:RELATES_TO]->(e2:Entity)
                WHERE e1.name IN $names AND e2.name IN $names
                RETURN e1.name AS source, e2.name AS target,
                       r.type AS rel_type, r.count AS weight
                ORDER BY weight DESC
            """, {"names": list(top.keys())})
            relationships = [dict(r) for r in rels]

        else:
            # ── Co-occurrence mode — week filter applies here ──
            if week:
                if kw_list:
                    res = session.run("""
                        MATCH (a:Article {week:$week})-[:MENTIONS]->(e:Entity)
                        WHERE any(kw IN $kw_list WHERE toLower(e.name) CONTAINS kw)
                        WITH COLLECT(DISTINCT e) AS seed
                        UNWIND seed AS e
                        MATCH (e)-[:CO_OCCURS_WITH]-(other:Entity)
                        WITH COLLECT(DISTINCT e)+COLLECT(DISTINCT other) AS nl
                        UNWIND nl AS node WITH DISTINCT node
                        MATCH (node)-[r:CO_OCCURS_WITH]-()
                        WHERE r.weekly_counts_json CONTAINS $week
                        WITH node, COUNT(r) AS conn
                        ORDER BY conn DESC LIMIT 25
                        RETURN node.name AS name, node.type AS type, conn
                    """, {"week": week, "kw_list": kw_list})
                else:
                    res = session.run("""
                        MATCH (a:Article {week:$week})-[:MENTIONS]->(e:Entity)
                        WITH DISTINCT e
                        MATCH (e)-[r:CO_OCCURS_WITH]-()
                        WHERE r.weekly_counts_json CONTAINS $week
                        WITH e, COUNT(r) AS conn
                        ORDER BY conn DESC LIMIT 25
                        RETURN e.name AS name, e.type AS type, conn
                    """, {"week": week})
            else:
                if kw_list:
                    res = session.run("""
                        MATCH (e:Entity)
                        WHERE any(kw IN $kw_list WHERE toLower(e.name) CONTAINS kw)
                        WITH e
                        MATCH (e)-[:CO_OCCURS_WITH]-(other:Entity)
                        WITH collect(DISTINCT e)+collect(DISTINCT other) AS nl
                        UNWIND nl AS node WITH DISTINCT node
                        MATCH (node)-[r:CO_OCCURS_WITH]-()
                        WITH node, COUNT(r) AS conn
                        ORDER BY conn DESC LIMIT 25
                        RETURN node.name AS name, node.type AS type, conn
                    """, {"kw_list": kw_list})
                else:
                    res = session.run("""
                        MATCH (node:Entity)-[r:CO_OCCURS_WITH]-()
                        WITH node, COUNT(r) AS conn
                        ORDER BY conn DESC LIMIT 25
                        RETURN node.name AS name, node.type AS type, conn
                    """)
            top = {r["name"]: r for r in res}

            if week:
                rels = session.run("""
                    MATCH (e1:Entity)-[r:CO_OCCURS_WITH]-(e2:Entity)
                    WHERE e1.name IN $names AND e2.name IN $names
                    AND r.weekly_counts_json IS NOT NULL
                    RETURN e1.name AS source, e2.name AS target,
                           r.weekly_counts_json AS wcj
                """, {"names": list(top.keys())})
                relationships = []
                for r in rels:
                    try:
                        wc = json.loads(r["wcj"]) if r["wcj"] else {}
                    except:
                        wc = {}
                    w = wc.get(week, 0)
                    if w >= 1:
                        relationships.append({
                            "source": r["source"], "target": r["target"],
                            "weight": w, "rel_type": "CO_OCCURS_WITH"
                        })
            else:
                rels = session.run("""
                    MATCH (e1:Entity)-[r:CO_OCCURS_WITH]-(e2:Entity)
                    WHERE e1.name IN $names AND e2.name IN $names AND r.count >= 3
                    RETURN e1.name AS source, e2.name AS target, r.count AS weight
                """, {"names": list(top.keys())})
                relationships = [{
                    "source": r["source"], "target": r["target"],
                    "weight": r["weight"], "rel_type": "CO_OCCURS_WITH"
                } for r in rels]

    # ── Build PyVis network ──
    # Labels hidden on edges — relationship type shown on hover only
    # Increased spring length and reduced gravity for cleaner layout
    net = Network(height="480px", width="100%", bgcolor="#0A0C0F",
                  font_color="#8A9BB0", notebook=False, cdn_resources="in_line")
    net.set_options("""
    {
      "physics": {
        "forceAtlas2Based": {
          "gravitationalConstant": -120,
          "centralGravity": 0.005,
          "springLength": 260,
          "springConstant": 0.03,
          "damping": 0.9
        },
        "solver": "forceAtlas2Based",
        "stabilization": {"iterations": 200, "fit": true},
        "minVelocity": 0.75
      },
      "edges": {
        "smooth": {"type": "continuous"},
        "color": {"opacity": 0.6},
        "arrows": {"to": {"enabled": true, "scaleFactor": 0.3}},
        "font": {"size": 0}
      },
      "nodes": {
        "borderWidth": 1,
        "borderWidthSelected": 3
      },
      "interaction": {
        "hover": true,
        "tooltipDelay": 100
      }
    }
    """)

    for name, data in top.items():
        is_india = (name == "India")
        is_seed  = bool(kw_list and any(kw in name.lower() for kw in kw_list))
        color    = "#E8D5A3" if is_india else TYPE_COLORS.get(data["type"], "#5A6A7A")
        border   = "#FFFFFF" if is_india else ("#E8D5A3" if is_seed else color)
        size     = 58 if is_india else (40 if is_seed else min(12 + data["conn"] * 1.8, 38))
        net.add_node(name, label=name,
            color={
                "background":  color,
                "border":      border,
                "highlight":   {"background": "#E8D5A3", "border": "#FFFFFF"}
            },
            size=size,
            title=f"{data['type']} · {data['conn']} connections",
            font={"size": 11, "color": "#C8D4E0", "face": "IBM Plex Mono"})

    for r in relationships:
        if r["source"] in top and r["target"] in top:
            rel_type   = r.get("rel_type", "CO_OCCURS_WITH")
            edge_color = RELATION_COLORS.get(rel_type, "#3A5068")
            # Relationship label only on hover via title — keeps graph clean
            net.add_edge(
                r["source"], r["target"],
                value=min((r["weight"] or 1) * 0.4, 4),
                title=rel_type.replace("_", " ") + "  (" + str(r["weight"]) + "x)",
                color={"color": edge_color, "highlight": "#E8D5A3"},
            )

    net.save_graph("graph_visual.html")
    with open("graph_visual.html", "r") as f:
        return f.read()
# ── [END: GRAPH VISUALIZER] ─────────────────────────────────────


# ── [SECTION: PAGE CONFIG] ──────────────────────────────────────
st.set_page_config(
    page_title="PRAJNA - Strategic Intelligence",
    page_icon="*",
    layout="wide",
    initial_sidebar_state="collapsed"
)
# ── [END: PAGE CONFIG] ──────────────────────────────────────────


# ── [SECTION: CSS] ──────────────────────────────────────────────
st.markdown("""
<style>
@import url('https://fonts.googleapis.com/css2?family=IBM+Plex+Mono:wght@300;400;500;600&family=IBM+Plex+Sans:wght@300;400;500;600&display=swap');
*, *::before, *::after { box-sizing: border-box; }
html, body, .stApp { background-color: #0A0C0F !important; color: #C8D4E0 !important; font-family: 'IBM Plex Sans', sans-serif !important; }
#MainMenu, footer, header { visibility: hidden; }
.stDeployButton { display: none; }
section[data-testid="stSidebar"] { display: none; }
.prajna-nav { display: flex; align-items: center; justify-content: space-between; padding: 0 0 20px 0; border-bottom: 1px solid #1C2A38; margin-bottom: 20px; }
.prajna-logo { font-family: 'IBM Plex Mono', monospace; font-size: 13px; font-weight: 600; letter-spacing: 0.25em; color: #E8D5A3; text-transform: uppercase; }
.prajna-logo span { color: #4A6A8A; margin: 0 12px; }
.prajna-meta { font-family: 'IBM Plex Mono', monospace; font-size: 10px; color: #3A5068; letter-spacing: 0.1em; text-transform: uppercase; }
.prajna-status { display: flex; align-items: center; gap: 6px; font-family: 'IBM Plex Mono', monospace; font-size: 10px; color: #4A8A6A; letter-spacing: 0.1em; }
.status-dot { width: 6px; height: 6px; background: #4A8A6A; border-radius: 50%; animation: pulse 2s infinite; }
@keyframes pulse { 0%,100% { opacity:1; } 50% { opacity:0.3; } }
.stTabs [data-baseweb="tab-list"] { background: transparent !important; border-bottom: 1px solid #1C2A38 !important; gap: 0 !important; padding: 0 !important; }
.stTabs [data-baseweb="tab"] { font-family: 'IBM Plex Mono', monospace !important; font-size: 10px !important; font-weight: 500 !important; letter-spacing: 0.15em !important; text-transform: uppercase !important; color: #3A5068 !important; background: transparent !important; border: none !important; border-bottom: 2px solid transparent !important; padding: 10px 20px !important; border-radius: 0 !important; }
.stTabs [aria-selected="true"] { color: #E8D5A3 !important; border-bottom: 2px solid #E8D5A3 !important; background: transparent !important; }
.stTabs [data-baseweb="tab-panel"] { padding-top: 24px !important; background: transparent !important; }
.stTextInput > div > div > input { background: #0D1117 !important; border: 1px solid #1C2A38 !important; border-radius: 0 !important; color: #C8D4E0 !important; font-family: 'IBM Plex Mono', monospace !important; font-size: 13px !important; padding: 10px 14px !important; }
.stTextInput > div > div > input:focus { border-color: #C8A96E !important; box-shadow: none !important; }
.stTextInput label { font-family: 'IBM Plex Mono', monospace !important; font-size: 9px !important; text-transform: uppercase !important; letter-spacing: 0.15em !important; color: #3A5068 !important; }
.stSelectbox > div > div { background: #0D1117 !important; border: 1px solid #1C2A38 !important; border-radius: 0 !important; color: #C8D4E0 !important; font-family: 'IBM Plex Mono', monospace !important; font-size: 11px !important; }
.stSelectbox label { font-family: 'IBM Plex Mono', monospace !important; font-size: 9px !important; text-transform: uppercase !important; letter-spacing: 0.15em !important; color: #3A5068 !important; }
.stButton > button { background: transparent !important; border: 1px solid #2A3A4A !important; border-radius: 0 !important; color: #8A9BB0 !important; font-family: 'IBM Plex Mono', monospace !important; font-size: 10px !important; font-weight: 500 !important; letter-spacing: 0.15em !important; text-transform: uppercase !important; padding: 8px 20px !important; transition: all 0.15s ease !important; }
.stButton > button:hover { background: #1C2A38 !important; border-color: #C8A96E !important; color: #E8D5A3 !important; }
.stButton > button:focus { box-shadow: none !important; outline: none !important; }
.stSlider > div > div > div { background: #1C2A38 !important; }
.stSlider label { font-family: 'IBM Plex Mono', monospace !important; font-size: 9px !important; text-transform: uppercase !important; letter-spacing: 0.15em !important; color: #3A5068 !important; }
.brief-container { border: 1px solid #1C2A38; border-left: 3px solid #C8A96E; background: #0D1117; padding: 20px 24px; margin: 16px 0; font-family: 'IBM Plex Sans', sans-serif; font-size: 13px; line-height: 1.8; color: #A8B8C8; }
.brief-header { font-family: 'IBM Plex Mono', monospace; font-size: 9px; color: #C8A96E; text-transform: uppercase; letter-spacing: 0.2em; margin-bottom: 14px; padding-bottom: 10px; border-bottom: 1px solid #1C2A38; }
.path-node { display: flex; align-items: center; gap: 12px; padding: 10px 16px; margin: 2px 0; background: #0D1117; border: 1px solid #1C2A38; font-family: 'IBM Plex Mono', monospace; font-size: 12px; color: #C8D4E0; }
.path-node.start { border-left: 3px solid #6B8CAE; }
.path-node.end { border-left: 3px solid #C8A96E; }
.path-node.mid { border-left: 3px solid #2A3A4A; margin-left: 20px; }
.path-connector { margin-left: 28px; padding: 4px 16px; font-family: 'IBM Plex Mono', monospace; font-size: 10px; color: #2A4A3A; letter-spacing: 0.1em; }
.source-tag { font-family: 'IBM Plex Mono', monospace; font-size: 9px; color: #3A5068; border: 1px solid #1C2A38; padding: 3px 8px; letter-spacing: 0.08em; text-transform: uppercase; }
.surge-card { border: 1px solid #1C2A38; border-left: 3px solid #8A4A3A; background: #0D1117; padding: 16px 20px; margin: 8px 0; }
.surge-entity { font-family: 'IBM Plex Mono', monospace; font-size: 13px; font-weight: 600; color: #E8D5A3; letter-spacing: 0.1em; text-transform: uppercase; }
.surge-ratio { font-family: 'IBM Plex Mono', monospace; font-size: 11px; color: #C87B6A; margin-top: 2px; }
.section-label { font-family: 'IBM Plex Mono', monospace; font-size: 9px; color: #3A5068; text-transform: uppercase; letter-spacing: 0.2em; margin-bottom: 12px; padding-bottom: 8px; border-bottom: 1px solid #1C2A38; }
div[data-testid="metric-container"] { background: #0D1117 !important; border: 1px solid #1C2A38 !important; border-radius: 0 !important; padding: 12px 16px !important; }
div[data-testid="metric-container"] label { font-family: 'IBM Plex Mono', monospace !important; font-size: 9px !important; text-transform: uppercase !important; letter-spacing: 0.15em !important; color: #3A5068 !important; }
div[data-testid="metric-container"] div[data-testid="stMetricValue"] { font-family: 'IBM Plex Mono', monospace !important; font-size: 20px !important; color: #E8D5A3 !important; }
::-webkit-scrollbar { width: 4px; }
::-webkit-scrollbar-track { background: #0A0C0F; }
::-webkit-scrollbar-thumb { background: #1C2A38; }
.stSpinner > div { border-top-color: #C8A96E !important; }
.stAlert { background: #0D1117 !important; border: 1px solid #1C2A38 !important; border-radius: 0 !important; font-family: 'IBM Plex Mono', monospace !important; font-size: 11px !important; color: #5A7A9A !important; }
.stDownloadButton > button { background: #0D1117 !important; border: 1px solid #C8A96E !important; color: #C8A96E !important; font-family: 'IBM Plex Mono', monospace !important; font-size: 10px !important; letter-spacing: 0.15em !important; text-transform: uppercase !important; padding: 8px 20px !important; border-radius: 0 !important; }
.stDownloadButton > button:hover { background: #C8A96E !important; color: #0A0C0F !important; }
</style>
""", unsafe_allow_html=True)
# ── [END: CSS] ──────────────────────────────────────────────────


# ── [SECTION: NAV BAR] ──────────────────────────────────────────
now_str = datetime.now(timezone.utc).strftime("%Y-%m-%d  %H:%M UTC")
try:
    articles_n, entities_n, rels_n, semantic_n = get_stats()
except:
    articles_n, entities_n, rels_n, semantic_n = 0, 0, 0, 0

logo_html = f'<img src="data:image/svg+xml;base64,{LOGO_B64}" width="52" height="52" style="opacity:0.95"/>' if LOGO_B64 else ""

st.markdown(f"""
<div class="prajna-nav">
    <div style="display:flex;align-items:center;gap:16px">
        {logo_html}
        <div>
            <div class="prajna-logo">PRAJNA<span>*</span>Strategic Intelligence Engine</div>
            <div class="prajna-meta" style="margin-top:4px">India Innovates 2026 &nbsp;·&nbsp; Domain 02: Digital Democracy &nbsp;·&nbsp; TeamIIMC</div>
        </div>
    </div>
    <div style="text-align:right">
        <div class="prajna-status"><div class="status-dot"></div>GRAPH ACTIVE</div>
        <div class="prajna-meta" style="margin-top:4px">{now_str}</div>
    </div>
</div>
""", unsafe_allow_html=True)
# ── [END: NAV BAR] ──────────────────────────────────────────────


# ── [SECTION: STATS ROW] ────────────────────────────────────────
c1, c2, c3, c4, c5 = st.columns(5)
c1.metric("ARTICLES INGESTED",  articles_n)
c2.metric("ENTITIES MAPPED",    entities_n)
c3.metric("CO-OCCURRENCE RELS", rels_n)
c4.metric("SEMANTIC RELS",      semantic_n)
c5.metric("GRAPH STATUS",       "● LIVE")
st.markdown("<div style='margin-bottom:8px'></div>", unsafe_allow_html=True)
# ── [END: STATS ROW] ────────────────────────────────────────────


# ── [SECTION: TABS] ─────────────────────────────────────────────
tab1, tab2, tab3, tab4, tab5 = st.tabs([
    "INTELLIGENCE BRIEF",
    "TRAJECTORY ANALYSIS",
    "PATH QUERY",
    "SURGE DETECTION",
    "WEEKLY BRIEF"
])
# ── [END: TABS] ─────────────────────────────────────────────────


# ── [SECTION: TAB 1 — INTELLIGENCE BRIEF] ───────────────────────
with tab1:
    col_left, col_right = st.columns([1, 1], gap="large")

    # ── Left: Query Interface ──
    with col_left:
        st.markdown('<div class="section-label">Query Interface</div>', unsafe_allow_html=True)
        if "query_input" not in st.session_state:
            st.session_state["query_input"] = ""
        query = st.text_input(
            "STRATEGIC QUESTION",
            placeholder="What are India's energy security risks from Iran?",
            value=st.session_state["query_input"]
        )
        st.markdown('<div style="margin:12px 0 8px;font-family:IBM Plex Mono;font-size:9px;color:#2A3A4A;letter-spacing:0.15em;text-transform:uppercase;">Suggested Queries</div>', unsafe_allow_html=True)
        demo_queries = [
            "India Iran energy security",
            "Pakistan Afghanistan India impact",
            "India China border tensions",
            "India Russia defense cooperation",
            "Israel Iran war implications",
        ]
        for dq in demo_queries:
            if st.button(dq.upper(), key=f"dq_{dq}"):
                st.session_state["query_input"] = dq
                st.rerun()
        st.markdown("<div style='margin-top:16px'></div>", unsafe_allow_html=True)
        run_query = st.button("EXECUTE QUERY", key="run_brief")

        if run_query and query:
            with st.spinner(""):
                keywords     = [w for w in query.lower().split() if len(w) > 3][:5]
                context      = get_graph_context(keywords)
                articles_ctx = get_articles(keywords)
                ctx_str      = "\n".join([f"  {e1} -{rel}-> {e2} (count:{s})" for e1, e2, rel, s in context])
                art_str      = "\n".join([f"  [{src}] {title}" for title, src in articles_ctx])
                prompt = (
                    "You are Prajna, India's strategic intelligence engine.\n"
                    "Answer ONLY from the semantic graph context below.\n\n"
                    "SEMANTIC RELATIONSHIPS:\n" + ctx_str + "\n\n"
                    "NEWS SOURCES:\n" + art_str + "\n\n"
                    "QUESTION: " + query + "\n\n"
                    "SITUATION — 2-3 sentence summary\n"
                    "KEY CONNECTIONS — 3-4 bullet points, cite relationship types\n"
                    "STRATEGIC IMPLICATIONS — what this means for India\n"
                    "RECOMMENDED ACTION — one concrete action for Indian policymakers\n"
                    "SOURCES — list all cited sources"
                )
                brief = ask_groq(prompt)
            sources_html = ""
            if articles_ctx:
                tags = "".join([f'<span class="source-tag">{src}</span>' for _, src in articles_ctx[:6]])
                sources_html = '<div style="display:flex;flex-wrap:wrap;gap:6px;margin-top:12px;padding-top:12px;border-top:1px solid #1C2A38">' + tags + '</div>'
            st.markdown(
                '<div class="brief-container"><div class="brief-header">INTELLIGENCE BRIEF &nbsp;·&nbsp; '
                + datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
                + ' &nbsp;·&nbsp; ' + str(len(context)) + ' semantic connections analysed</div>'
                + brief.replace("\n", "<br>") + sources_html + '</div>',
                unsafe_allow_html=True
            )
        elif run_query and not query:
            st.warning("Enter a strategic question first.")

    # ── Right: Knowledge Graph ──
    with col_right:
        st.markdown('<div class="section-label">Knowledge Graph</div>', unsafe_allow_html=True)

        # ── [SECTION: TAB 1 — GRAPH CONTROLS] ───────────────────
        c_filter, c_mode, c_week = st.columns([2, 1, 1])
        with c_filter:
            graph_filter = st.text_input(
                "FILTER BY ENTITY",
                placeholder="China, India, Russia  (comma separated)",
                key="graph_filter"
            )
        with c_mode:
            graph_mode = st.selectbox(
                "VIEW MODE",
                ["SEMANTIC", "CO-OCCURRENCE"],
                key="graph_mode"
            )
        with c_week:
            # Week selector disabled in semantic mode
            # RELATES_TO has no week property — week filtering only works on CO_OCCURS_WITH
            if graph_mode == "SEMANTIC":
                st.selectbox(
                    "WEEK  (co-occ only)",
                    ["N/A — semantic"],
                    key="graph_week_disabled",
                    disabled=True
                )
                selected_week = "ALL TIME"
            else:
                selected_week = st.selectbox(
                    "WEEK",
                    ["ALL TIME"] + get_available_weeks(),
                    key="graph_week"
                )

        week_param = None if selected_week == "ALL TIME" else strip_week_label(selected_week)
        mode_param = "semantic" if graph_mode == "SEMANTIC" else "cooccurrence"
        # ── [END: TAB 1 — GRAPH CONTROLS] ───────────────────────

        with st.spinner(""):
            try:
                graph_html = build_graph_visual(
                    keyword=graph_filter or None,
                    week=week_param if mode_param == "cooccurrence" else None,
                    mode=mode_param
                )
                components.html(graph_html, height=480)

                if mode_param == "semantic":
                    if graph_filter:
                        st.markdown(
                            '<div style="font-family:IBM Plex Mono;font-size:9px;color:#C8A96E;margin-top:6px">'
                            'Showing: ' + graph_filter.upper() + ' and direct connections &nbsp;·&nbsp; Hover edges for relationship type'
                            '</div>',
                            unsafe_allow_html=True
                        )
                    legend_items = [
                        ("#C87B6A", "CONFLICT / THREAT"),
                        ("#C8956A", "MILITARY"),
                        ("#C8B86A", "SANCTIONS / OPPOSE"),
                        ("#6B8CAE", "TRADE / ECONOMIC"),
                        ("#4A8A6A", "ALLIANCE / SUPPORT"),
                        ("#8A6AAE", "GOVERNANCE"),
                        ("#4A8AAA", "DIPLOMACY"),
                    ]
                    legend_html = '<div style="display:flex;flex-wrap:wrap;gap:8px;margin-top:6px">'
                    for color, label in legend_items:
                        legend_html += '<div style="display:flex;align-items:center;gap:4px;font-family:IBM Plex Mono;font-size:8px;color:' + color + '"><div style="width:8px;height:8px;background:' + color + ';border-radius:50%"></div>' + label + '</div>'
                    legend_html += '</div>'
                    st.markdown(legend_html, unsafe_allow_html=True)
                else:
                    week_label = f"Showing: {selected_week}" if week_param else "Showing: All time"
                    st.markdown(
                        '<div style="font-family:IBM Plex Mono;font-size:9px;color:#2A3A4A;text-transform:uppercase;letter-spacing:0.1em;margin-top:8px">'
                        + week_label + ' &nbsp;·&nbsp; Node size = connection strength'
                        '</div>',
                        unsafe_allow_html=True
                    )
            except Exception as e:
                st.error(f"Graph error: {e}")
# ── [END: TAB 1] ────────────────────────────────────────────────


# ── [SECTION: TAB 2 — TRAJECTORY ANALYSIS] ──────────────────────
with tab2:
    st.markdown('<div class="section-label">Relationship Trajectory Analysis</div>', unsafe_allow_html=True)
    st.markdown('<div style="font-family:IBM Plex Mono;font-size:10px;color:#3A5068;margin-bottom:20px;line-height:1.7">Tracks co-occurrence strength between two entities week-over-week.<br>Sustained increases = deepening relationship. Spikes = event-driven. Drops = decoupling.</div>', unsafe_allow_html=True)

    c1, c2, c3 = st.columns([2, 2, 1])
    with c1: e1 = st.text_input("ENTITY A", value="India", key="traj_e1")
    with c2: e2 = st.text_input("ENTITY B", value="Iran",  key="traj_e2")
    with c3:
        st.markdown("<div style='margin-top:28px'></div>", unsafe_allow_html=True)
        run_traj = st.button("RUN ANALYSIS", key="run_traj")
    st.markdown('<div style="font-family:IBM Plex Mono;font-size:9px;color:#2A3A4A;letter-spacing:0.1em;margin-bottom:16px">SUGGESTED — India/Iran &nbsp;·&nbsp; India/Russia &nbsp;·&nbsp; Iran/Israel &nbsp;·&nbsp; India/China &nbsp;·&nbsp; Pakistan/Afghanistan</div>', unsafe_allow_html=True)

    if run_traj:
        with st.spinner(""):
            weekly_data, total = get_trajectory(e1, e2)

        if not weekly_data:
            st.markdown('<div style="font-family:IBM Plex Mono;font-size:11px;color:#5A3A3A;border:1px solid #2A1A1A;padding:14px 18px;background:#0D0A0A">NO TRAJECTORY DATA — ' + e1.upper() + ' vs ' + e2.upper() + '</div>', unsafe_allow_html=True)
        else:
            st.markdown('<div style="font-family:IBM Plex Mono;font-size:10px;color:#4A6A4A;border:1px solid #1A2A1A;padding:10px 16px;background:#0A0D0A;margin-bottom:16px">' + e1.upper() + ' vs ' + e2.upper() + ' &nbsp;·&nbsp; ' + str(total) + ' TOTAL &nbsp;·&nbsp; ' + str(len(weekly_data)) + ' WEEKS OF DATA</div>', unsafe_allow_html=True)
            df = pd.DataFrame(weekly_data, columns=["Week", "Co-occurrences"])
            st.bar_chart(df.set_index("Week"), color="#C8A96E")

            # Semantic relationships between the two entities
            with driver.session() as session:
                sem_rels = session.run("""
                    MATCH (a:Entity {name:$e1})-[r:RELATES_TO]->(b:Entity {name:$e2})
                    RETURN r.type AS rel, r.count AS cnt
                    UNION
                    MATCH (a:Entity {name:$e2})-[r:RELATES_TO]->(b:Entity {name:$e1})
                    RETURN r.type AS rel, r.count AS cnt
                    ORDER BY cnt DESC
                """, {"e1": e1, "e2": e2}).data()

            if sem_rels:
                sem_html = '<div style="margin-bottom:16px"><div style="font-family:IBM Plex Mono;font-size:9px;color:#3A5068;text-transform:uppercase;letter-spacing:0.15em;margin-bottom:8px">Semantic Relationships</div>'
                for r in sem_rels:
                    color = RELATION_COLORS.get(r["rel"], "#3A5068")
                    sem_html += '<div style="display:flex;align-items:center;gap:10px;padding:6px 12px;border:1px solid #1C2A38;margin:2px 0;background:#0D1117"><span style="font-family:IBM Plex Mono;font-size:9px;font-weight:600;color:' + color + ';letter-spacing:0.1em">' + r["rel"] + '</span><span style="font-family:IBM Plex Mono;font-size:9px;color:#3A5068">' + str(r["cnt"]) + 'x</span></div>'
                sem_html += '</div>'
                st.markdown(sem_html, unsafe_allow_html=True)

            traj_str = "\n".join([f"  {w}: {c}" for w, c in weekly_data])
            sem_str  = "\n".join([f"  {r['rel']}: {r['cnt']}x" for r in sem_rels]) if sem_rels else "  None extracted"
            prompt = (
                "You are Prajna. Analyse this relationship:\n\n"
                + e1 + " vs " + e2 + "\n\n"
                "Weekly co-occurrence data:\n" + traj_str + "\n"
                "Total: " + str(total) + "\n\n"
                "Semantic relationship types:\n" + sem_str + "\n\n"
                "SITUATION — is this relationship intensifying, cooling, or volatile?\n"
                "RELATIONSHIP TYPE — what kind of relationship based on semantic data?\n"
                "INFLECTION POINTS — sharp changes and likely geopolitical causes\n"
                "INDIA STRATEGIC IMPLICATIONS — what does this mean for India?\n"
                "WATCH FOR — 2 specific developments to monitor\n\n"
                "Be analytical and specific. Max 250 words."
            )
            with st.spinner(""):
                brief = ask_groq(prompt)
            st.markdown('<div class="brief-container"><div class="brief-header">TRAJECTORY — ' + e1.upper() + ' vs ' + e2.upper() + '</div>' + brief.replace("\n", "<br>") + '</div>', unsafe_allow_html=True)
# ── [END: TAB 2] ────────────────────────────────────────────────


# ── [SECTION: TAB 3 — PATH QUERY & SEMANTIC EXPLORER] ───────────
with tab3:
    st.markdown('<div class="section-label">Path Query  &  Semantic Explorer</div>', unsafe_allow_html=True)
    subtab1, subtab2 = st.tabs(["GRAPH PATH QUERY", "ENTITY SEMANTIC PROFILE"])

    # ── Subtab 1: Shortest path via CO_OCCURS_WITH ──
    with subtab1:
        st.markdown('<div style="font-family:IBM Plex Mono;font-size:10px;color:#3A5068;margin-bottom:20px;line-height:1.7">Finds the shortest connection path between any two entities in the knowledge graph.</div>', unsafe_allow_html=True)
        c1, c2, c3 = st.columns([2, 2, 1])
        with c1: p1 = st.text_input("ORIGIN ENTITY",  value="India",   key="path_p1")
        with c2: p2 = st.text_input("TARGET ENTITY",  value="Taliban", key="path_p2")
        with c3:
            st.markdown("<div style='margin-top:28px'></div>", unsafe_allow_html=True)
            run_path = st.button("FIND PATH", key="run_path")
        st.markdown('<div style="font-family:IBM Plex Mono;font-size:9px;color:#2A3A4A;letter-spacing:0.1em;margin-bottom:16px">SUGGESTED — India/Taliban &nbsp;·&nbsp; Russia/Taliban &nbsp;·&nbsp; Israel/Pakistan &nbsp;·&nbsp; India/Qatar</div>', unsafe_allow_html=True)

        if run_path:
            with st.spinner(""):
                path = find_path(p1, p2)
            if not path:
                st.markdown('<div style="font-family:IBM Plex Mono;font-size:11px;color:#5A3A3A;border:1px solid #2A1A1A;padding:14px 18px;background:#0D0A0A">NO PATH FOUND — ' + p1.upper() + ' to ' + p2.upper() + '</div>', unsafe_allow_html=True)
            else:
                nodes     = path["nodes"]
                strengths = path["strengths"]
                st.markdown('<div style="font-family:IBM Plex Mono;font-size:10px;color:#4A6A4A;border:1px solid #1A2A1A;padding:10px 16px;background:#0A0D0A;margin-bottom:16px">PATH FOUND &nbsp;·&nbsp; ' + str(path["hops"]) + ' HOPS &nbsp;·&nbsp; ' + p1.upper() + ' to ' + p2.upper() + '</div>', unsafe_allow_html=True)
                nodes_html = ""
                path_str   = ""
                for i, node in enumerate(nodes):
                    if i == 0:
                        nodes_html += '<div class="path-node start">  ' + node.upper() + '</div>'
                        path_str   += node
                    elif i == len(nodes) - 1:
                        nodes_html += '<div class="path-node end">  ' + node.upper() + '</div>'
                        path_str   += node
                    else:
                        nodes_html += '<div class="path-node mid">  ' + node + '</div>'
                        path_str   += node
                    if i < len(strengths):
                        nodes_html += '<div class="path-connector">co-occurs ' + str(strengths[i]) + 'x in news</div>'
                        path_str   += " --[" + str(strengths[i]) + "x]--> "
                st.markdown(nodes_html, unsafe_allow_html=True)
                prompt = (
                    "You are Prajna. A knowledge graph path query revealed:\n\n"
                    "PATH: " + path_str + "\n"
                    "HOPS: " + str(path["hops"]) + "\n\n"
                    "Each arrow = two entities co-appearing in real news articles.\n\n"
                    "HIDDEN CONNECTION — what does this path mean in plain English?\n"
                    "STRATEGIC SIGNIFICANCE — why does this matter for India?\n"
                    "NON-OBVIOUS INSIGHT — what would an analyst miss without this graph?\n"
                    "RECOMMENDED ACTION — one concrete action for Indian policymakers\n\n"
                    "Be direct and specific. Max 220 words."
                )
                with st.spinner(""):
                    brief = ask_groq(prompt)
                st.markdown('<div class="brief-container" style="margin-top:16px"><div class="brief-header">PATH INTELLIGENCE — ' + p1.upper() + ' to ' + p2.upper() + '</div>' + brief.replace("\n", "<br>") + '</div>', unsafe_allow_html=True)

    # ── Subtab 2: Entity semantic profile ──
    with subtab2:
        st.markdown('<div style="font-family:IBM Plex Mono;font-size:10px;color:#3A5068;margin-bottom:20px;line-height:1.7">Full semantic relationship profile for any entity — all typed relationships from the knowledge graph.</div>', unsafe_allow_html=True)
        c1, c2 = st.columns([3, 1])
        with c1:
            entity_search = st.text_input("ENTITY NAME", value="India", key="sem_entity")
        with c2:
            st.markdown("<div style='margin-top:28px'></div>", unsafe_allow_html=True)
            run_sem = st.button("EXPLORE", key="run_sem")

        if run_sem:
            with st.spinner(""):
                outgoing, incoming = get_semantic_relations(entity_search)
            if not outgoing and not incoming:
                st.markdown('<div style="font-family:IBM Plex Mono;font-size:11px;color:#5A3A3A;border:1px solid #2A1A1A;padding:14px 18px;background:#0D0A0A">NO SEMANTIC RELATIONSHIPS FOUND FOR ' + entity_search.upper() + '</div>', unsafe_allow_html=True)
            else:
                col_out, col_in = st.columns(2)
                with col_out:
                    st.markdown('<div style="font-family:IBM Plex Mono;font-size:9px;color:#C8A96E;text-transform:uppercase;letter-spacing:0.15em;margin-bottom:8px">' + entity_search.upper() + ' acts on</div>', unsafe_allow_html=True)
                    for r in outgoing:
                        color = RELATION_COLORS.get(r["rel"], "#3A5068")
                        st.markdown(
                            '<div style="display:flex;justify-content:space-between;align-items:center;padding:8px 12px;border:1px solid #1C2A38;border-left:3px solid ' + color + ';margin:2px 0;background:#0D1117">'
                            '<span style="font-family:IBM Plex Mono;font-size:10px;color:#C8D4E0">' + r["target"] + '</span>'
                            '<span style="font-family:IBM Plex Mono;font-size:8px;font-weight:600;color:' + color + ';letter-spacing:0.08em">' + r["rel"] + '</span>'
                            '<span style="font-family:IBM Plex Mono;font-size:9px;color:#3A5068">' + str(r["cnt"]) + 'x</span>'
                            '</div>',
                            unsafe_allow_html=True
                        )
                with col_in:
                    st.markdown('<div style="font-family:IBM Plex Mono;font-size:9px;color:#6B8CAE;text-transform:uppercase;letter-spacing:0.15em;margin-bottom:8px">acts on ' + entity_search.upper() + '</div>', unsafe_allow_html=True)
                    for r in incoming:
                        color = RELATION_COLORS.get(r["rel"], "#3A5068")
                        st.markdown(
                            '<div style="display:flex;justify-content:space-between;align-items:center;padding:8px 12px;border:1px solid #1C2A38;border-left:3px solid ' + color + ';margin:2px 0;background:#0D1117">'
                            '<span style="font-family:IBM Plex Mono;font-size:10px;color:#C8D4E0">' + r["source"] + '</span>'
                            '<span style="font-family:IBM Plex Mono;font-size:8px;font-weight:600;color:' + color + ';letter-spacing:0.08em">' + r["rel"] + '</span>'
                            '<span style="font-family:IBM Plex Mono;font-size:9px;color:#3A5068">' + str(r["cnt"]) + 'x</span>'
                            '</div>',
                            unsafe_allow_html=True
                        )
                sem_out_str = "\n".join([f"  {entity_search} -{r['rel']}-> {r['target']} ({r['cnt']}x)" for r in outgoing])
                sem_in_str  = "\n".join([f"  {r['source']} -{r['rel']}-> {entity_search} ({r['cnt']}x)" for r in incoming])
                prompt = (
                    "You are Prajna. Analyse this entity's full semantic relationship profile:\n\n"
                    "ENTITY: " + entity_search + "\n\n"
                    "OUTGOING RELATIONSHIPS:\n" + sem_out_str + "\n\n"
                    "INCOMING RELATIONSHIPS:\n" + sem_in_str + "\n\n"
                    "ENTITY PROFILE — describe this entity's role in the geopolitical landscape\n"
                    "KEY RELATIONSHIPS — most strategically significant connections\n"
                    "INDIA ANGLE — how does this entity's position affect India specifically?\n"
                    "WATCH — one development involving this entity to monitor\n\n"
                    "Be analytical. Max 200 words."
                )
                with st.spinner(""):
                    brief = ask_groq(prompt)
                st.markdown('<div class="brief-container" style="margin-top:16px"><div class="brief-header">SEMANTIC PROFILE — ' + entity_search.upper() + '</div>' + brief.replace("\n", "<br>") + '</div>', unsafe_allow_html=True)
# ── [END: TAB 3] ────────────────────────────────────────────────


# ── [SECTION: TAB 4 — SURGE DETECTION] ──────────────────────────
with tab4:
    st.markdown('<div class="section-label">Automated Surge Detection</div>', unsafe_allow_html=True)
    st.markdown('<div style="font-family:IBM Plex Mono;font-size:10px;color:#3A5068;margin-bottom:20px;line-height:1.7">Monitors the knowledge graph for entities whose news co-occurrence is growing anomalously fast.</div>', unsafe_allow_html=True)

    c1, c2 = st.columns([2, 1])
    with c1:
        threshold = st.slider("SURGE THRESHOLD (x WEEKLY BASELINE)", 1.2, 3.0, 1.5, 0.1)
    with c2:
        st.markdown("<div style='margin-top:28px'></div>", unsafe_allow_html=True)
        run_surge = st.button("SCAN GRAPH", key="run_surge")

    if run_surge:
        with st.spinner(""):
            surges = detect_surges(threshold=threshold)

        if not surges:
            st.markdown('<div style="font-family:IBM Plex Mono;font-size:11px;color:#3A5068;border:1px solid #1C2A38;padding:14px 18px;background:#0D1117">NO SURGES DETECTED ABOVE ' + str(threshold) + 'x THRESHOLD</div>', unsafe_allow_html=True)
            # Fallback — top entities by connection strength
            with driver.session() as session:
                top = session.run("""
                    MATCH (e:Entity)-[r:CO_OCCURS_WITH]-()
                    WHERE e.type IN ['GPE','ORG','PERSON']
                    RETURN e.name AS name, e.type AS type, count(r) AS conn
                    ORDER BY conn DESC LIMIT 12
                """).data()
            rows_html = "".join([
                '<div style="display:flex;justify-content:space-between;padding:6px 12px;border-bottom:1px solid #0D1117;font-family:IBM Plex Mono;font-size:10px;color:#5A7A9A"><span>' + r["name"].upper() + '</span><span style="color:#3A5068">' + str(r["conn"]) + ' connections</span></div>'
                for r in top if len(r["name"]) < 35
            ])
            st.markdown('<div style="border:1px solid #1C2A38;background:#0D1117">' + rows_html + '</div>', unsafe_allow_html=True)
        else:
            st.markdown('<div style="font-family:IBM Plex Mono;font-size:10px;color:#C87B6A;border:1px solid #2A1A1A;padding:10px 16px;background:#0D0A0A;margin-bottom:16px">' + str(len(surges)) + ' ENTITIES FLAGGED ABOVE ' + str(threshold) + 'x BASELINE</div>', unsafe_allow_html=True)
            for surge in surges:
                st.markdown('<div class="surge-card"><div class="surge-entity">' + surge["entity"] + '</div><div class="surge-ratio">' + str(surge["ratio"]) + 'x baseline &nbsp;·&nbsp; ' + str(surge["latest"]) + ' this week &nbsp;·&nbsp; baseline: ' + str(surge["baseline"]) + '/week</div></div>', unsafe_allow_html=True)
                prompt = (
                    "Prajna surge alert:\n"
                    "Entity: " + surge["entity"] + " (" + surge["type"] + ")\n"
                    "This week: " + str(surge["latest"]) + " co-occurrences\n"
                    "Baseline: " + str(surge["baseline"]) + " per week\n"
                    "Surge ratio: " + str(surge["ratio"]) + "x\n\n"
                    "SURGE EXPLANATION — why is this entity surging?\n"
                    "INDIA RISK/OPPORTUNITY — strategic implications for India?\n"
                    "URGENCY — Immediate / Days / Weeks\n"
                    "RECOMMENDED ACTION — one specific action\n\n"
                    "Max 130 words. Be direct."
                )
                with st.spinner(""):
                    brief = ask_groq(prompt)
                st.markdown('<div class="brief-container" style="border-left-color:#8A4A3A;margin-bottom:20px"><div class="brief-header" style="color:#C87B6A">SURGE BRIEF — ' + surge["entity"].upper() + '</div>' + brief.replace("\n", "<br>") + '</div>', unsafe_allow_html=True)
# ── [END: TAB 4] ────────────────────────────────────────────────


# ── [SECTION: TAB 5 — WEEKLY BRIEF] ─────────────────────────────
with tab5:
    st.markdown('<div class="section-label">Automated Weekly Intelligence Brief</div>', unsafe_allow_html=True)
    st.markdown('<div style="font-family:IBM Plex Mono;font-size:10px;color:#3A5068;margin-bottom:20px">Prajna automatically identifies the 5 most strategically significant developments India should monitor — zero user input required.</div>', unsafe_allow_html=True)

    available_weeks_brief = get_available_weeks()
    week_options_brief    = ["CURRENT WEEK"] + available_weeks_brief
    c1b, c2b = st.columns([2, 1])
    with c1b:
        selected_brief_week = st.selectbox("SELECT WEEK FOR BRIEF", week_options_brief, key="brief_week")
    with c2b:
        st.markdown("<div style='margin-top:28px'></div>", unsafe_allow_html=True)
        run_weekly_brief = st.button("GENERATE BRIEF", key="run_weekly_brief")

    if run_weekly_brief:
        brief_week = get_week_key() if selected_brief_week == "CURRENT WEEK" else selected_brief_week

        with st.spinner("Analysing graph..."):
            with driver.session() as session:
                # Top entities for the selected week
                top_entities = session.run(
                    "MATCH (a:Article {week:$w})-[:MENTIONS]->(e:Entity) "
                    "WHERE e.type IN ['GPE','ORG','PERSON','NORP'] "
                    "AND NOT e.name IN ['United States','United Kingdom','Guardian','BBC','Reuters','AP','AFP'] "
                    "RETURN e.name AS entity, e.type AS type, COUNT(a) AS mentions "
                    "ORDER BY mentions DESC LIMIT 15",
                    {"w": brief_week}
                ).data()
                names = [r["entity"] for r in top_entities]

                # Top co-occurring pairs for the week
                pairs = session.run(
                    "MATCH (a:Article {week:$w})-[:MENTIONS]->(e1:Entity) "
                    "MATCH (a)-[:MENTIONS]->(e2:Entity) "
                    "WHERE e1.name IN $names AND e2.name IN $names AND e1.name < e2.name "
                    "RETURN e1.name AS e1, e2.name AS e2, COUNT(a) AS co_count "
                    "ORDER BY co_count DESC LIMIT 20",
                    {"w": brief_week, "names": names}
                ).data()
                top_pairs = pairs[:5]

                # Supporting headlines per pair
                headlines = {}
                for p in top_pairs:
                    arts = session.run(
                        "MATCH (a:Article {week:$w})-[:MENTIONS]->(x:Entity {name:$e1}) "
                        "MATCH (a)-[:MENTIONS]->(y:Entity {name:$e2}) "
                        "RETURN a.title AS title, a.source AS source LIMIT 3",
                        {"w": brief_week, "e1": p["e1"], "e2": p["e2"]}
                    ).data()
                    headlines[p["e1"] + " and " + p["e2"]] = arts

                # Semantic context for those entities
                sem_context = session.run(
                    "MATCH (e1:Entity)-[r:RELATES_TO]->(e2:Entity) "
                    "WHERE e1.name IN $names AND e2.name IN $names "
                    "RETURN e1.name AS e1, r.type AS rel, e2.name AS e2, r.count AS cnt "
                    "ORDER BY cnt DESC LIMIT 20",
                    {"names": names}
                ).data()

            # Build prompt context strings
            pairs_lines = ["Most active relationships this week:"]
            for p in top_pairs:
                pairs_lines.append("  " + p["e1"] + " and " + p["e2"] + ": " + str(p["co_count"]) + " co-mentions")
            hl_lines = ["Supporting headlines:"]
            for key, arts in headlines.items():
                hl_lines.append(key + ":")
                for a in arts:
                    hl_lines.append("  [" + a["source"] + "] " + a["title"])
            sem_lines = ["Semantic relationships:"]
            for r in sem_context:
                sem_lines.append("  " + r["e1"] + " -[" + r["rel"] + "]-> " + r["e2"] + " (" + str(r["cnt"]) + "x)")

            # On-screen brief — shorter, 400 words
            prompt = (
                "You are Prajna, India's strategic intelligence engine.\n"
                "Week: " + brief_week + "\n\n"
                + "\n".join(pairs_lines) + "\n\n"
                + "\n".join(hl_lines) + "\n\n"
                + "\n".join(sem_lines) + "\n\n"
                "Generate a WEEKLY INTELLIGENCE BRIEF for Indian policymakers.\n\n"
                "WEEK " + brief_week + " - STRATEGIC INTELLIGENCE BRIEF\n\n"
                "STORY 1: [headline]\n[2-3 sentences on why this matters for India]\n\n"
                "STORY 2: [headline]\n[2-3 sentences]\n\n"
                "STORY 3: [headline]\n[2-3 sentences]\n\n"
                "STORY 4: [headline]\n[2-3 sentences]\n\n"
                "STORY 5: [headline]\n[2-3 sentences]\n\n"
                "BOTTOM LINE FOR INDIA: One sentence strategic summary.\n\n"
                "Be direct, analytical, India-centric. Max 400 words."
            )
            brief_text = ask_groq(prompt, max_tokens=800)

        # Display on-screen brief
        all_sources = []
        for arts in headlines.values():
            for a in arts:
                if a["source"] not in all_sources:
                    all_sources.append(a["source"])
        src_str = "  ".join(["[" + s + "]" for s in all_sources[:8]])
        header  = "WEEKLY BRIEF - " + brief_week + " - " + str(len(top_pairs)) + " signal pairs - " + str(len(names)) + " entities"
        st.markdown(
            '<div class="brief-container"><div class="brief-header">' + header + '</div>'
            + brief_text.replace("\n", "<br>")
            + '<div style="margin-top:12px;padding-top:12px;border-top:1px solid #1C2A38;font-family:IBM Plex Mono;font-size:9px;color:#3A5068">' + src_str + '</div></div>',
            unsafe_allow_html=True
        )

        # PDF — detailed version, 700 words, includes semantic context
        with st.spinner("Generating PDF..."):
            detailed_prompt = (
                "You are Prajna, India's strategic intelligence engine.\n"
                "Week: " + brief_week + "\n\n"
                + "\n".join(pairs_lines) + "\n\n"
                + "\n".join(hl_lines) + "\n\n"
                + "\n".join(sem_lines) + "\n\n"
                "Generate a DETAILED WEEKLY INTELLIGENCE BRIEF for Indian policymakers.\n\n"
                "WEEK " + brief_week + " - STRATEGIC INTELLIGENCE BRIEF\n\n"
                "EXECUTIVE SUMMARY\n"
                "[3-4 sentence overview of the most critical developments]\n\n"
                "STORY 1: [headline]\n[4-5 sentences: what happened, why it matters, India's exposure]\n\n"
                "STORY 2: [headline]\n[4-5 sentences]\n\n"
                "STORY 3: [headline]\n[4-5 sentences]\n\n"
                "STORY 4: [headline]\n[4-5 sentences]\n\n"
                "STORY 5: [headline]\n[4-5 sentences]\n\n"
                "STRATEGIC RISK MATRIX\n"
                "HIGH RISK: [one line]\n"
                "MEDIUM RISK: [one line]\n"
                "OPPORTUNITY: [one line]\n\n"
                "BOTTOM LINE FOR INDIA: Two sentence strategic summary.\n\n"
                "Be direct, analytical, India-centric. Max 700 words."
            )
            detailed_brief = ask_groq(detailed_prompt, max_tokens=1200)
            pdf_bytes = generate_pdf_brief(brief_week, top_pairs, headlines, detailed_brief, names)

        st.download_button(
            label="DOWNLOAD DETAILED BRIEF (PDF)",
            data=pdf_bytes,
            file_name="Prajna_Brief_" + brief_week + ".pdf",
            mime="application/pdf"
        )
# ── [END: TAB 5] ────────────────────────────────────────────────
